on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Loging to Docker"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: "testing actions"
        run: pwd

      - name: "printing name"
        run: echo 'Ashraf maged'

      - name: "listing folder content"
        run: ls -a
