on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "testing actions"
        run: pwd
      - name: "printing name"
        run: echo 'Ashraf maged'
      - name: "listing folder content"
        run: ls
      - uses: actions/checkout@v3
      - name: "listing folder content"
        run: ls
