on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Loging to Docker"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password${{secrets.DOCKER_TOKEN}}
      - name: "testing actions"
        run: pwd

      - name: "printing name"
        run: echo 'Ashraf maged'

      - uses: actions/checkout@v3

      - name: "listing folder content"
        run: ls -a
